```{r}
library(tidymodels)
library(tidyverse)
library(ggplot2)
library(kknn)
library(yardstick)
library(themis)
library(glmnet)
library(rpart.plot)

load("../RDAfiles/splitrecipefold.rda")
```

# Set up the work flows

```{r}
# Knn
knn_mod <- nearest_neighbor(neighbors = tune()) %>%
  set_mode("classification") %>%
  set_engine("kknn")

knn_wkflow <- workflow() %>% 
  add_model(knn_mod) %>% 
  add_recipe(LoL_recipe)

# Logistic
log_reg <- logistic_reg() %>% 
  set_engine("glm") %>% 
  set_mode("classification")

log_wkflow <- workflow() %>% 
  add_model(log_reg) %>% 
  add_recipe(LoL_recipe)

# Elastic Net
glm_mod <- logistic_reg(mixture = tune(), penalty = tune()) %>%
  set_mode("classification") %>%
  set_engine("glmnet")

glm_wkflow <- workflow() %>% 
  add_model(glm_mod) %>% 
  add_recipe(LoL_recipe)

# Tree
tree_spec <- decision_tree(cost_complexity = tune()) %>%
  set_engine("rpart") %>% 
  set_mode("classification")

tree_wf <- workflow() %>% 
  add_model(tree_spec) %>% 
  add_recipe(LoL_recipe)

# tune grids
neighbors_grid <- grid_regular(neighbors(range = c(1, 10)), levels = 10)
glm_grid <- grid_regular(penalty(range = c(0, 1), trans = identity_trans()), mixture(range = c(0, 1)), levels = 10)
tree_grid <- grid_regular(cost_complexity(range = c(-3, -1)), levels = 10)
```

# model fitting
```{r}
tune_tree <- tune_grid(
  tree_wf, 
  resamples = df_folds, 
  grid = tree_grid
)

knn_res <- tune_grid(
  object = knn_wkflow, 
  resamples = df_folds, 
  grid = neighbors_grid
)

log_res <- fit_resamples(
  object = log_wkflow, 
  resamples = df_folds
)

glm_res <- tune_grid(
  object = glm_wkflow, 
  resamples = df_folds, 
  grid = glm_grid,
  control = control_grid(verbose = TRUE)
)
```


```{r}
autoplot(tune_tree)

collect_metrics(tune_tree)

best_complexity <- select_best(tune_tree)

tree_final <- finalize_workflow(tree_wf, best_complexity)

tree_final_fit <- fit(tree_final, data = df_train)

tree_final_fit %>%
  extract_fit_engine() %>%
  rpart.plot()
```
```{r}
tree_final_fit
```

```{r}
metrics <- metric_set(roc_auc)
augment(tree_final_fit, new_data = df_test) %>%
  metrics(blueWins, .pred_0)

show_best(knn_res, metric = "roc_auc")
show_best(log_res, metric = "roc_auc")
show_best(glm_res, metric = "roc_auc")
show_best(tune_tree, metric = "roc_auc")
```

